EMB_cb_allemb_001_41148123:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 512
    dataset_id: EMB_2
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 256
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.0001
    metrics: [rec_loss, all_loss]
    model: VQVAEAllEmb
    model_alpha: 0.1
    model_beta: 0.1
    model_root: ./checkpoints/EMB_cb_allemb5_std/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.1
    net_regularizer: 0
    num_embeddings: 1024
    num_workers: 3
    optimizer: adam
    output_dim: 512
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
