DIN_MicroLens_1M_x1_001_342a8149:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: ReLU
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    batch_norm: true
    batch_size: 384
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    din_use_softmax: false
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 3
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    learning_rate: 0.0001
    loss: binary_crossentropy
    max_len: 64
    metrics: [AUC, logloss]
    model: DIN
    model_root: ./checkpoints/baseline_std/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DIN_MicroLens_1M_x1_002_44d425b9:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: ReLU
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    batch_norm: true
    batch_size: 384
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    din_use_softmax: false
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 3
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    learning_rate: 0.0001
    loss: binary_crossentropy
    max_len: 64
    metrics: [AUC, logloss]
    model: DIN
    model_root: ./checkpoints/baseline_std/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DIN_MicroLens_1M_x1_003_8b5f4fb4:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: ReLU
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    batch_norm: true
    batch_size: 384
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    din_use_softmax: false
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 3
    embedding_dim: 64
    embedding_regularizer: 1.0e-07
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    learning_rate: 0.0001
    loss: binary_crossentropy
    max_len: 64
    metrics: [AUC, logloss]
    model: DIN
    model_root: ./checkpoints/baseline_std/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DIN_MicroLens_1M_x1_004_0faf7daa:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: ReLU
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    batch_norm: true
    batch_size: 384
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    din_use_softmax: false
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 3
    embedding_dim: 64
    embedding_regularizer: 1.0e-07
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    learning_rate: 0.0001
    loss: binary_crossentropy
    max_len: 64
    metrics: [AUC, logloss]
    model: DIN
    model_root: ./checkpoints/baseline_std/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DIN_MicroLens_1M_x1_005_457fe531:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: ReLU
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    batch_norm: true
    batch_size: 384
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    din_use_softmax: false
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 3
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    learning_rate: 1.0e-05
    loss: binary_crossentropy
    max_len: 64
    metrics: [AUC, logloss]
    model: DIN
    model_root: ./checkpoints/baseline_std/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DIN_MicroLens_1M_x1_006_066699aa:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: ReLU
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    batch_norm: true
    batch_size: 384
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    din_use_softmax: false
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 3
    embedding_dim: 64
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    learning_rate: 1.0e-05
    loss: binary_crossentropy
    max_len: 64
    metrics: [AUC, logloss]
    model: DIN
    model_root: ./checkpoints/baseline_std/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DIN_MicroLens_1M_x1_007_d516fa82:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: ReLU
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    batch_norm: true
    batch_size: 384
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    din_use_softmax: false
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 3
    embedding_dim: 64
    embedding_regularizer: 1.0e-07
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    learning_rate: 1.0e-05
    loss: binary_crossentropy
    max_len: 64
    metrics: [AUC, logloss]
    model: DIN
    model_root: ./checkpoints/baseline_std/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.2
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
DIN_MicroLens_1M_x1_008_0f724815:
    accumulation_steps: 1
    attention_dropout: 0.1
    attention_hidden_activations: ReLU
    attention_hidden_units: [512, 256]
    attention_output_activation: null
    batch_norm: true
    batch_size: 384
    dataset_id: MicroLens_1M_x1
    debug_mode: false
    din_use_softmax: false
    dnn_activations: ReLU
    dnn_hidden_units: [1024, 512, 256]
    early_stop_patience: 3
    embedding_dim: 64
    embedding_regularizer: 1.0e-07
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    learning_rate: 1.0e-05
    loss: binary_crossentropy
    max_len: 64
    metrics: [AUC, logloss]
    model: DIN
    model_root: ./checkpoints/baseline_std/
    monitor: AUC
    monitor_mode: max
    net_dropout: 0.3
    net_regularizer: 0
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    task: binary_classification
    use_features: null
    verbose: 1
