EMB_2:
    data_format: parquet
    data_root: ./data/
    feature_cols:
    - {active: true, dtype: int, name: likes_level, source: item, type: categorical,
        vocab_size: 11}
    - {active: true, dtype: int, name: views_level, source: item, type: categorical,
        vocab_size: 11}
    - {active: true, dtype: int, embedding_dim: 768, name: txt_emb_BERT, source: item,
        type: embedding}
    - {active: true, dtype: int, embedding_dim: 1024, name: img_emb_CLIPRN50, source: item,
        type: embedding}
    - {active: true, dtype: int, max_len: 5, name: item_tags, source: item, type: sequence,
        vocab_size: 11740}
    item_info: ./dataset/MicroLens_1M_MMCTR/item_feature.parquet
    label_col: {dtype: float, name: label}
    rebuild_dataset: false
    tags_pad_len: 5
    train_data: ./data/EMB_2/train.parquet
    valid_data: ./data/EMB_2/valid.parquet
