Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 3
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: user_id
    use_features: null
    feature_specs: null
    feature_config: null


EMB_cb_allemb: # This is a config template
    model_root: './checkpoints/EMB_cb_allemb/'
    model: VQVAEAllEmb
    dataset_id: EMB_2
    metrics: [rec_loss, all_loss]
    optimizer: adam
    learning_rate: 1.0e-5 # 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    model_alpha: 0.5
    model_beta: 0.5
    net_dropout: 0
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 20242025
    monitor: "rec_loss"
    monitor_mode: 'min'
    accumulation_steps: 1
    num_embeddings: 1024
    embedding_dim: 128
    hidden_dim: 512
    output_dim: 64