base_config: ./config/din_config/
base_expid: EMB_cb_allemb
dataset_id: EMB_2

dataset_config:
    EMB_2:
        data_root: ./data/
        data_format: parquet
        train_data: ./data/EMB_2/train.parquet
        valid_data: ./data/EMB_2/valid.parquet
        item_info: ./dataset/MicroLens_1M_MMCTR/item_feature.parquet
        rebuild_dataset: False
        feature_cols:
            - {name: likes_level, active: True, dtype: int, type: categorical, vocab_size: 11, source: item}
            - {name: views_level, active: True, dtype: int, type: categorical, vocab_size: 11, source: item}
            - {name: txt_emb_BERT, active: True, dtype: int, type: embedding,  embedding_dim: 768, source: item}
            - {name: img_emb_CLIPRN50, active: True, dtype: int, type: embedding, embedding_dim: 1024, source: item}
            - {name: item_tags, active: True, dtype: int, type: sequence, max_len: 7, vocab_size: 11740, source: item}
        label_col: {name: label, dtype: float}
        tags_pad_len: 5

tuner_space:
    embedding_regularizer: 1.e-6
    net_regularizer: 0
    net_dropout: [0.1, 0.2]
    learning_rate: [1.e-3, 1.e-4]
    batch_size: 512
    model_alpha: [0.1, 0.5]
    model_beta: 0.1
    num_embeddings: 1024
    output_dim: 512
    embedding_dim: 256
    model_root: './checkpoints/EMB_cb_allemb4/' 
    
