EMB_cb01_001_0b950f56:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 512
    dataset_id: EMB_1
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 1.0e-05
    metrics: [rec_loss, all_loss]
    model: VQVAE
    model_alpha: 0.1
    model_beta: 0.1
    model_root: ./checkpoints/emb_cb01/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.1
    net_regularizer: 0
    num_embeddings: 64
    num_workers: 3
    optimizer: adam
    output_dim: 1024
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
EMB_cb01_002_c3f52f5e:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 512
    dataset_id: EMB_1
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 1.0e-05
    metrics: [rec_loss, all_loss]
    model: VQVAE
    model_alpha: 0.5
    model_beta: 0.1
    model_root: ./checkpoints/emb_cb01/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.1
    net_regularizer: 0
    num_embeddings: 64
    num_workers: 3
    optimizer: adam
    output_dim: 1024
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
