EMB_cb01_001_5f45a4a6:
    accumulation_steps: 1
    alpha: 0.5
    batch_norm: true
    batch_size: 2048
    beta: 0.5
    dataset_id: EMB_1
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.001
    metrics: [rec_loss, all_loss]
    model: VQVAE
    model_root: ./checkpoints/emb_cb01/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.1
    net_regularizer: 0
    num_embeddings: 1024
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
EMB_cb01_002_1eb9a4df:
    accumulation_steps: 1
    alpha: 0.5
    batch_norm: true
    batch_size: 2048
    beta: 0.5
    dataset_id: EMB_1
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.0001
    metrics: [rec_loss, all_loss]
    model: VQVAE
    model_root: ./checkpoints/emb_cb01/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.1
    net_regularizer: 0
    num_embeddings: 1024
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
EMB_cb01_003_490f80ca:
    accumulation_steps: 1
    alpha: 0.5
    batch_norm: true
    batch_size: 2048
    beta: 0.5
    dataset_id: EMB_1
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 1.0e-05
    metrics: [rec_loss, all_loss]
    model: VQVAE
    model_root: ./checkpoints/emb_cb01/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.1
    net_regularizer: 0
    num_embeddings: 1024
    num_workers: 3
    optimizer: adam
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
