EMB_cb_allemb_001_3df4a779:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    dataset_id: EMB_2
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.001
    metrics: [rec_loss, all_loss]
    model: VQVAEAllEmb
    model_alpha: 0.1
    model_beta: 0.1
    model_root: ./checkpoints/EMB_cb_allemb2/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.1
    net_regularizer: 0
    num_embeddings: 64
    num_workers: 3
    optimizer: adam
    output_dim: 512
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
EMB_cb_allemb_002_5f8a80d2:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    dataset_id: EMB_2
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.001
    metrics: [rec_loss, all_loss]
    model: VQVAEAllEmb
    model_alpha: 0.1
    model_beta: 0.1
    model_root: ./checkpoints/EMB_cb_allemb2/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.2
    net_regularizer: 0
    num_embeddings: 64
    num_workers: 3
    optimizer: adam
    output_dim: 512
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
EMB_cb_allemb_003_65a7a0bc:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    dataset_id: EMB_2
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.001
    metrics: [rec_loss, all_loss]
    model: VQVAEAllEmb
    model_alpha: 0.5
    model_beta: 0.1
    model_root: ./checkpoints/EMB_cb_allemb2/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.1
    net_regularizer: 0
    num_embeddings: 64
    num_workers: 3
    optimizer: adam
    output_dim: 512
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
EMB_cb_allemb_004_50d9bc21:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    dataset_id: EMB_2
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.001
    metrics: [rec_loss, all_loss]
    model: VQVAEAllEmb
    model_alpha: 0.5
    model_beta: 0.1
    model_root: ./checkpoints/EMB_cb_allemb2/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.2
    net_regularizer: 0
    num_embeddings: 64
    num_workers: 3
    optimizer: adam
    output_dim: 512
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
EMB_cb_allemb_005_622530bc:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    dataset_id: EMB_2
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.0001
    metrics: [rec_loss, all_loss]
    model: VQVAEAllEmb
    model_alpha: 0.1
    model_beta: 0.1
    model_root: ./checkpoints/EMB_cb_allemb2/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.1
    net_regularizer: 0
    num_embeddings: 64
    num_workers: 3
    optimizer: adam
    output_dim: 512
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
EMB_cb_allemb_006_0fdd50ef:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    dataset_id: EMB_2
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.0001
    metrics: [rec_loss, all_loss]
    model: VQVAEAllEmb
    model_alpha: 0.1
    model_beta: 0.1
    model_root: ./checkpoints/EMB_cb_allemb2/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.2
    net_regularizer: 0
    num_embeddings: 64
    num_workers: 3
    optimizer: adam
    output_dim: 512
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
EMB_cb_allemb_007_59d81fa3:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    dataset_id: EMB_2
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.0001
    metrics: [rec_loss, all_loss]
    model: VQVAEAllEmb
    model_alpha: 0.5
    model_beta: 0.1
    model_root: ./checkpoints/EMB_cb_allemb2/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.1
    net_regularizer: 0
    num_embeddings: 64
    num_workers: 3
    optimizer: adam
    output_dim: 512
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
EMB_cb_allemb_008_1ce968f0:
    accumulation_steps: 1
    batch_norm: true
    batch_size: 2048
    dataset_id: EMB_2
    debug_mode: false
    early_stop_patience: 3
    embedding_dim: 128
    embedding_regularizer: 1.0e-06
    epochs: 100
    eval_steps: null
    feature_config: null
    feature_specs: null
    group_id: user_id
    hidden_dim: 512
    learning_rate: 0.0001
    metrics: [rec_loss, all_loss]
    model: VQVAEAllEmb
    model_alpha: 0.5
    model_beta: 0.1
    model_root: ./checkpoints/EMB_cb_allemb2/
    monitor: rec_loss
    monitor_mode: min
    net_dropout: 0.2
    net_regularizer: 0
    num_embeddings: 64
    num_workers: 3
    optimizer: adam
    output_dim: 512
    pickle_feature_encoder: true
    save_best_only: true
    seed: 20242025
    shuffle: true
    use_features: null
    verbose: 1
